<?php
require_once($_SERVER['DOCUMENT_ROOT'].
	"/modelo/Usuario.php");
require_once($_SERVER['DOCUMENT_ROOT'].
	"/Persistencia/UsuarioBanco.php");
require_once($_SERVER['DOCUMENT_ROOT'].
	"/modelo/Topico.php");
require_once($_SERVER['DOCUMENT_ROOT'].
	"/Persistencia/TopicoBanco.php");
require_once($_SERVER['DOCUMENT_ROOT'].
	"/persistencia/Banco.php");
require_once($_SERVER['DOCUMENT_ROOT'].
	"/persistencia/Persistente.php");
?>
